export const ProAPI = {
  Products: [
    {
      id: 1,
      img: "men-01.jpg",
      title: "Classic Spring",
      price: "$120.00",
    },
    {
      id: 2,
      img: "men-02.jpg",
      title: "Classic Spring",
      price: "$120.00",
    },
    {
      id: 3,
      img: "men-03.jpg",
      title: "Classic Spring",
      price: "$120.00",
    },
    {
      id: 4,
      img: "Women-01.jpg",
      title: "Classic Spring",
      price: "$120.00",
    },
    {
      id: 5,
      img: "Women-02.jpg",
      title: "Classic Spring",
      price: "$120.00",
    },
    {
      id: 6,
      img: "Women-03.jpg",
      title: "Classic Spring",
      price: "$120.00",
    },
    {
      id: 7,
      img: "kid-01.jpeg",
      title: "Classic Spring",
      price: "$120.00",
    },
    {
      id: 8,
      img: "kid-02.jpg",
      title: "Classic Spring",
      price: "$120.00",
    },
    {
      id: 9,
      img: "kid-03.jpg",
      title: "Classic Spring",
      price: "$120.00",
    },
  ],
  Men: [
    {
      id: 1,
      img: "men-01.jpg",
      title: "Classic Spring 1",
      price: "$10.00",
    },
    {
      id: 2,
      img: "men-02.jpg",
      title: "Classic Spring 2",
      price: "$20.00",
    },
    {
      id: 3,
      img: "men-03.jpg",
      title: "Classic Spring 3",
      price: "$50.00",
    },
    {
      id: 4,
      img: "men-01.jpg",
      title: "Classic Spring 4",
      price: "$70.00",
    },
    {
      id: 5,
      img: "men-02.jpg",
      title: "Classic Spring 5",
      price: "$120.00",
    },
    {
      id: 6,
      img: "men-03.jpg",
      title: "Classic Spring 6",
      price: "$100.00",
    },
    {
      id: 7,
      img: "men-01.jpg",
      title: "Classic Spring 7",
      price: "$180.00",
    },
    {
      id: 8,
      img: "men-02.jpg",
      title: "Classic Spring 8",
      price: "$20.00",
    },
  ],
  Women: [
    {
      id: 1,
      img: "women-01.jpg",
      title: "Classic Spring 1",
      price: "$10.00",
    },
    {
      id: 2,
      img: "women-02.jpg",
      title: "Classic Spring 2",
      price: "$20.00",
    },
    {
      id: 3,
      img: "women-03.jpg",
      title: "Classic Spring 3",
      price: "$50.00",
    },
    {
      id: 4,
      img: "women-01.jpg",
      title: "Classic Spring 4",
      price: "$70.00",
    },
    {
      id: 5,
      img: "women-02.jpg",
      title: "Classic Spring 5",
      price: "$120.00",
    },
    {
      id: 6,
      img: "women-03.jpg",
      title: "Classic Spring 6",
      price: "$100.00",
    },
    {
      id: 7,
      img: "women-01.jpg",
      title: "Classic Spring 7",
      price: "$180.00",
    },
    {
      id: 8,
      img: "women-02.jpg",
      title: "Classic Spring 8",
      price: "$20.00",
    },
  ],
  Kid: [
    {
      id: 1,
      img: "kid-01.jpeg",
      title: "Classic Spring 1",
      price: "$10.00",
    },
    {
      id: 2,
      img: "kid-02.jpg",
      title: "Classic Spring 2",
      price: "$20.00",
    },
    {
      id: 3,
      img: "kid-03.jpg",
      title: "Classic Spring 3",
      price: "$50.00",
    },
    {
      id: 4,
      img: "kid-01.jpeg",
      title: "Classic Spring 4",
      price: "$70.00",
    },
    {
      id: 5,
      img: "kid-02.jpg",
      title: "Classic Spring 5",
      price: "$120.00",
    },
    {
      id: 6,
      img: "kid-03.jpg",
      title: "Classic Spring 6",
      price: "$100.00",
    },
    {
      id: 7,
      img: "kid-01.jpeg",
      title: "Classic Spring 7",
      price: "$180.00",
    },
    {
      id: 8,
      img: "kid-02.jpg",
      title: "Classic Spring 8",
      price: "$20.00",
    },
  ],
};
